FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
COPY shared/package.json ./shared/
COPY server/package.json ./server/

RUN npm install

COPY shared ./shared
COPY server ./server

WORKDIR /app/server
EXPOSE 4000

CMD ["npm", "run", "dev"]
