name: Lighthouse CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g @lhci/cli@0.14.x
      - run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LHCI_URL: ${{ secrets.LHCI_URL }}
